### ISSUE TITLE
Documentation generator raises a `NameError`

### ISSUE THREAD

**Issue by majjoha** [interagent/prmd#263]
While the verification process works for our schemas, the documentation generator currently raises a `NameError`. Is this an error you are already familiar with?

The stack trace is as follows:
```
NameError: uninitialized constant Prmd::Link
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/templates/schemata/link.md.erb:16:in `result'
/Users/mathias/.gem/ruby/2.2.3/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
/Users/mathias/.gem/ruby/2.2.3/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/template.rb:64:in `render'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/templates/schemata.md.erb:35:in `block in result'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/templates/schemata.md.erb:33:in `each'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/templates/schemata.md.erb:33:in `result'
/Users/mathias/.gem/ruby/2.2.3/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
/Users/mathias/.gem/ruby/2.2.3/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/templates/schema.erb:7:in `block in result'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/templates/schema.erb:4:in `each'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/templates/schema.erb:4:in `map'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/templates/schema.erb:4:in `result'
/Users/mathias/.gem/ruby/2.2.3/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
/Users/mathias/.gem/ruby/2.2.3/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/core/renderer.rb:49:in `render'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/commands/render.rb:34:in `render'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/rake_tasks/doc.rb:53:in `render_file'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/rake_tasks/doc.rb:62:in `render_to_file'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/rake_tasks/doc.rb:79:in `block (2 levels) in define'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/rake_tasks/doc.rb:78:in `each'
/Users/mathias/.gem/ruby/2.2.3/gems/prmd-0.8.0/lib/prmd/rake_tasks/doc.rb:78:in `block in define'
Tasks: TOP => default => spec => schema => schema:doc
(See full trace by running task with --trace)
```

**Comment by geemus** [comment]
Hmm. I'm not seeing anything obvious, could you share the schema in question (or at least enough to reproduce)? Thanks.

**Comment by gunyarakun** [comment]
I faced the same problem majjoha reported.
I've uploaded the schema for causing the same error.
https://github.com/gunyarakun/prmd-issue-263

```
cd docs
rake
```
will reproduce the problem.

**Comment by geemus** [comment]
@gunyarakun thanks for the detailed example.

I think I was confusing myself by looking at master instead of 0.8.0. It worked for me against master but not 0.8.0, so I've now released 0.9.0 which should fix this. Sorry for the confusion.

**Comment by majjoha** [comment]
Thanks for your reply, @geemus. The new release did not seem to solve our issue, but I looked into it, and https://github.com/interagent/prmd/pull/268 seems to fix the problem. Do you mind taking a look at it?

**Comment by geemus** [comment]
merged the fix, will try for a release a bit later today
